# Site settings
title: Tom Stesco
description: Projects and thoughts on buildings, AI/ML tech, and our cybernetic lives.

url: https://tomstesco.com

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  I’m focused on how combined AI hardware and algorithmic advances are transforming industries, and the required engineering for it to work reliably.
  If these topics interest you feel free to get in contact over [email](mailto:tom.stesco@gmail.com) or [LinkedIn](https://www.linkedin.com/in/tomstesco/).

email: tom.stesco@gmail.com
linkedin: tomstesco
github: tstesco
resume: tstesco_resume_2025_05_10.pdf

relevant_tags: ['hardware', 'software', 'buildings']

resume_url: 

author: Tom Stesco
author_title: Senior Staff Field Application Engineer, AI/ML software @ Tenstorrent

author_photo: headshot_2024_compressed.jpg
user_description_short: |
  I’m currently a Senior Staff Field Application Engineer at [Tenstorrent](https://www.tenstorrent.com), a company that builds AI computers for customers that care about owning their future.
  I build customer-facing application software and support customers in running their business on Tenstorrent hardware.
  I earned an MSc from ETH Zürich and a BASc from the University of Waterloo.
  My interests are in virtuous feedback between machines, people, and their environment.  
  
highlighter: pygments.rb
markdown: kramdown
## Disqus (commented out to disable)
#disqus_identifier: xxxx

## Tracker
google_analytics_id: UA-119019898-1

keywords: 'software,hardware,engineer,AI,ML,machine learning,cybernetics,buildings,cities,design,'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']